import "../styles/globals.css";
import 'bootstrap/dist/css/bootstrap.css';

import type { AppProps } from "next/app";
import LoaderContextProvider from "../contexts/loaderContext";
import AuthContextProvider, { AuthContext } from "../contexts/authContext";
import LoaderComponent from "../components/loaderComponent";
import { useContext, useEffect, useState } from "react";
import Head from "next/head";
import Script from "next/script";
import { userInfo } from "os";
import ConnectToMetamask from "../components/ConnectToMetamask";

function AuthIntialize() {
	const { user, checkStatus } = useContext(AuthContext);

	useEffect(() => {
		checkStatus();
	}, []);

	useEffect(() => {
		if (user.logged) {
			console.log("User is logged in");
		} else {
			console.log("User is not logged in");
		}
		console.log(user);
	}, [user]);

	return <></>;
}

function MyApp({ Component, pageProps }: AppProps) {
	
	return (
		<AuthContextProvider>
			<AuthIntialize />
			<LoaderContextProvider>
				<Head>
					<title>NextJS | Template</title>
					<meta
						name="description"
						content="Generated by create next app"
					/>
					<link rel="icon" href="/favicon.ico" />
					<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossOrigin="anonymous"></link>
				</Head>
				
				<LoaderComponent />
				<Component {...pageProps} />
				<ConnectToMetamask />
				<Script>
				<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossOrigin="anonymous"></script>

				</Script>
			</LoaderContextProvider>
		</AuthContextProvider>
	);
}

export default MyApp;
